### ISSUE TITLE
[docs] 为什么不修改 repo_url 呢？

### ISSUE THREAD

**Issue by Snoopy1866** [Xiaokang2022/tkintertools-docs#27]
据我所知，`mkdocs` 这里的 `repo_url` 链接并非一定要是仓库链接，改成 `tkintertools` 仓库链接就可以不用在下面写提示了
https://github.com/Xiaokang2022/tkintertools-docs/blob/d5a46069767bb68527166b5c241b6ae6c4c19043/3.0/mkdocs.yml#L3

![image](https://github.com/user-attachments/assets/2cb3ae9a-16a0-4e76-994d-1bd4adbfd84e)

我自己的仓库就是这么写的，没什么问题啊
https://github.com/PyStatPower/PyStatPower-Docs/blob/main/mkdocs.yml

**Comment by Xiaokang2022** [comment]
之前试过，但不知道为什么，这个一改，单页页面右上部分的“查看本页的源代码”和“编辑此页”的链接也会被同步改变，导致这俩按钮的功能失效。

刚刚测试了一下，仍然是这样的，不清楚为什么你的可以做到。

**Comment by Xiaokang2022** [comment]
刚查了一下 Mkdocs-Material 的文档，以及和你的配置文件对比后，发现除了要改这个 `repo_url` 之外，还要修改 `edit_uri`

**Comment by Xiaokang2022** [comment]
已修改，将关闭该 Issue
